---
# tasks file for gnu-tools

# install
- block:
  - name: update homebrew
    homebrew: update_homebrew=yes

  - name: install packages
    homebrew: name="{{ item.name }}" state="{{ install_state }}"
              install_options="{{ item.install_option|default(omit) }}"
    with_items: "{{ gnu_tools }}"
    tags:
      - install
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - update
